sonar.projectKey=localscan
sonar.projectName=localscan
sonar.projectVersion=1.0

# Base directory for scanning
sonar.sources=src

# Exclude unit test files and node_modules
sonar.exclusions=**/*.spec.ts,node_modules/**

# Set encoding and language
sonar.sourceEncoding=UTF-8
sonar.language=ts
